/* TEST-ONLY (simulator build of Build 62 (TestFlight 1.1); never shipped). Writes 1.0 user data that the 1.0 code
   itself created (web v235, headless run of saveCurrentMix, Notched Save profile, Sculptor save, theme button, master
   slider, Experiments favourite), reloads so 1.0 reads it, then prints what 1.0 holds: "B60SEED <tag> <json>". */
(function () {
  if (location.pathname.replace(/\/index\.html$/, "/") !== "/") return;
  var SEED = {"softwave:mixes": "[{\"id\":\"mx1791066585272_0\",\"name\":\"My rain + brown\",\"mix\":[{\"id\":\"rain\",\"volume\":0.5,\"balance\":0},{\"id\":\"brown\",\"volume\":0.3,\"balance\":0}],\"master\":0.85,\"timer\":{\"min\":0,\"fade\":true},\"saved\":1791066585272},{\"id\":\"mx1791066587101_1\",\"name\":\"Ocean evening\",\"mix\":[{\"id\":\"ocean\",\"volume\":0.6,\"balance\":0}],\"master\":0.85,\"timer\":{\"min\":0,\"fade\":true},\"saved\":1791066587101,\"visual\":\"underwater\"}]", "softwave:master": "0.85", "softwave:theme": "\"light\"", "softwave:rasterMs": "10", "softwave:match": "{\"freq\":6200,\"type\":\"tone\",\"balance\":0,\"when\":\"2026-10-03T22:29:48.312Z\"}", "softwave:metrics": "{\"sound_saved\":1}", "softwave:notch:profiles": "[{\"id\":1791066593971,\"name\":\"Evening notch\",\"created\":\"2026-10-03T22:29:53.971Z\",\"hz\":2597,\"where\":\"left\",\"conf\":\"low\",\"source\":\"pink\",\"width\":\"standard\",\"depth\":\"standard\",\"spec\":{\"centerHz\":2597,\"widthOct\":1,\"lowHz\":1836,\"highHz\":3673,\"attenuationDb\":24,\"design\":[{\"f\":1914.3385786524948,\"Q\":7.8,\"g\":-12.96},{\"f\":2597,\"Q\":6.24,\"g\":-22.56},{\"f\":3523.1014383816037,\"Q\":7.8,\"g\":-12.96}],\"master\":0.85,\"limiter\":\"threshold -10 dB, knee 12, ratio 8\",\"smoothing\":\"setTargetAtTime tau 0.08 s\",\"srAssumed\":48000}}]", "softwave:lab:feedback": "{\"generative\":{\"tries\":1,\"last\":1791066604162}}", "softwave:lab:favs": "[\"generative\"]", "softwave:notch:measures": "[{\"hz\":2597,\"where\":\"left\",\"conf\":\"low\",\"date\":\"2026-10-03T22:29:53.255Z\"}]", "softwave:lab:sounds": "[{\"type\":\"sculpt\",\"params\":{\"colour\":0.4,\"warm\":0,\"deep\":0,\"smooth\":0,\"soft\":0,\"width\":0.35,\"moving\":0,\"rich\":0,\"mod\":0},\"nature\":\"none\",\"natureVol\":0.35,\"name\":\"Soft hush\",\"when\":1791066599211}]", "softwave:volhint": "1", "softwave:playcounts": "{\"rain\":1,\"brown\":2,\"ocean\":2}", "softwave:rasterSlow": "0", "softwave:welcomed": "true", "softwave:lab:settings:generative": "{\"base\":\"ocean\",\"organic\":35}", "softwave:journey": "{\"step\":2,\"done\":false,\"dismissed\":false}", "softwave:lab:prefs2": "{\"n\":12,\"sum\":{\"colour\":4.8,\"warm\":1.2,\"deep\":0.6,\"smooth\":2.4,\"soft\":1.2,\"width\":4.2,\"moving\":2.4,\"rich\":3.6,\"mod\":1.8},\"natures\":{\"rain\":5}}"};
  var out = function (line) { console.log(line); try { fetch("http://127.0.0.1:8799/", { method: "POST", mode: "no-cors", body: line }); } catch (e) { } };
  var L = function (t, o) { out("B60SEED " + t + " " + JSON.stringify(o)); };
  if (!localStorage.getItem("__b61seeded")) { localStorage.clear(); for (var k in SEED) localStorage.setItem(k, SEED[k]); localStorage.setItem("__b61seeded", "1"); L("written", Object.keys(SEED).length); location.reload(); return; }
  window.addEventListener("load", function () { setTimeout(function () {
    var o = {}; for (var i = 0; i < localStorage.length; i++) { var k = localStorage.key(i); if (k.indexOf("softwave:") === 0) o[k] = localStorage.getItem(k); }
    var t = document.body.innerText;
    L("ui", { version: "1.1 (62)", journey: localStorage.getItem("softwave:journey"), mix: t.indexOf("My rain + brown") >= 0, session: t.indexOf("Ocean evening") >= 0, sound: t.indexOf("Soft hush") >= 0, theme: document.documentElement.dataset.theme, master: window.softwave && softwave.masterVolume });
    L("dump", o); out("B60SEED done");
  }, 6000); });
})();
